displayName: Responder
type: provider
iconPath: .assets/icon.png

import: github.com/gabay/responder

summary: 'Serve HTTP requests directly in traefik'

testData:
  defaultStatus: 204
  responses:
    - rule: "Host(`example.com`)"
      body: "OK"
      status: 200
      priority: 10
      headers:
        Content-Type: text/plain
      middlewares:
        - my-middleware@file
